AWSTemplateFormatVersion: '2010-09-09'
Description: 'QA SageMaker Endpoint'
Parameters:
  ModelName:
    Description: The name of the model that you want to host. This is the name that you specified when creating the model.
    MaxLength: '63'
    MinLength: '1'
    Type: String
  ModelDataUrl:
    Description: The S3 path where the model artifacts, which result from model training, are stored.
    MaxLength: '1024'
    MinLength: '1'
    Type: String
  EndpointName:
    Description: The name of the endpoint. The name must be unique within an AWS Region in your AWS account.
    MaxLength: '63'
    MinLength: '1'
    Type: String
  EndpointConfigName:
    Description: The name of the EndpointConfig resource that specifies the configuration for the endpoint.     
    MaxLength: '63'
    MinLength: '1'
    Type: String
  SageMakerRole:
    Description: Name of SageMaker role
    MaxLength: '64'
    MinLength: '1'
    Type: String
  SageMakerImage:
    Description: Name of SageMaker training image
    MaxLength: '256'
    MinLength: '1'
    Type: String
  SageMakerInstanceType:
    Default: ml.t2.medium
    Description: Type of Instance for SageMaker inference
    MaxLength: '64'
    MinLength: '1'
    Type: String
Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    DeletionPolicy: Delete
    Properties:
      ModelName: !Sub ${ModelName}
      ExecutionRoleArn: !Sub ${SageMakerRole}
      PrimaryContainer:
        ModelDataUrl: !Sub ${ModelDataUrl}
        Image: !Sub ${SageMakerImage}
  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    DependsOn: EndpointConfig
    DeletionPolicy: Delete
    Properties:
      EndpointName: !Sub ${EndpointName}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    DependsOn: Model
    DeletionPolicy: Delete
    Properties:
        EndpointConfigName: !Sub ${EndpointConfigName}
        ProductionVariants:
        - ModelName: !GetAtt Model.ModelName
          VariantName: AllTraffic
          InitialInstanceCount: 1
          InstanceType: !Sub ${SageMakerInstanceType}
          InitialVariantWeight: 1